# syntax=docker/dockerfile1.2

ARG UBUNTU_VERSION=18.04
ARG UBUNTU_IMAGE="ubuntu:${UBUNTU_VERSION}"

# Build container based on Ubuntu 18.04
FROM ${UBUNTU_IMAGE} AS base
RUN echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
ARG ATP_MIIOR
RUN echo 'Acquire::http::proxy "http://child-prc.intel.com:913/";' > /etc/apt/apt.conf.d/proxy.conf
RUN echo 'Acquire::https::proxy "http://child-prc.intel.com:913/";' >> /etc/apt/apt.conf.d/proxy.conf
RUN echo 'Acquire::ftp::proxy "ftp://child-prc.intel.com:913/";' >> /etc/apt/apt.conf.d/proxy.conf 
RUN echo 'Acquire::socks::proxy "socks://child-prc.intel.com:913/";' >> /etc/apt/apt.conf.d/proxy.conf
ENV http_proxy=http://child-prc.intel.com:913
ENV https_proxy=http://child-prc.intel.com:913

FROM base AS ACRN

WORKDIR /Workspace
COPY misc/ /Workspace/misc
RUN useradd -ms /bin/bash  acrn
RUN apt-get update \
    && apt-get install -y python3 \
    			  python3-pip \
			  libxml2-dev \
			  && apt-get clean

RUN pip3 install kconfiglib --proxy=http://child-prc.intel.com:913
RUN pip3 install -r /Workspace/misc/config_tools/config_app/requirements --proxy=http://child-prc.intel.com:913

EXPOSE 5001/udp
EXPOSE 5001/tcp
USER acrn
CMD [ "python3", "/Workspace/misc/config_tools/config_app/app.py" ]
